export { default as aboutMe } from "./aboutMe";
export { default as home } from "./home";
export { default as contact } from "./contact";
export { default as ownerProfile } from "./ownerProfile";
export { default as sitterProfile } from "./sitterProfile";
export { default as service } from "./service";
export { default as review } from "./review";
export { default as nav } from "./nav";
export { default as signup } from "./signup";
